apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  type: ClusterIP
  selector:
    app: books-service
  ports:
    - name: books-service
      port: 4003
      targetPort: 4003
      protocol: TCP
