apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: auth-service
      port: 4002
      targetPort: 4002
      protocol: TCP
