apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

labels:
  - pairs:
      environment: minikube
    includeSelectors: true
    includeTemplates: false

resources:
  - ./auth-service
  - ./books-service
  - ./gateway-service
  - ./notification-service

  - ./thirdparty/elasticsearch
  - ./thirdparty/kibana
  - ./thirdparty/postgresql
  - ./thirdparty/rabbitmq

  - ./secrets/backend-secrets.yaml
  - ./secrets/default-secret-token.yaml

  - ./namespace.yaml
